# Generated by Django 6.0.7 on 2026-09-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvscan',
            name='cv_file',
        ),
        migrations.AlterField(
            model_name='cvscan',
            name='cv_text',
            field=models.TextField(),
        ),
    ]
