# Generated by Django 6.0.7 on 2026-09-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cvscan_cv_file_alter_cvscan_cv_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_uri', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('preferred_label', models.CharField(db_index=True, max_length=500)),
                ('alt_labels', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('skill_type', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('esco', 'ESCO'), ('builtin', 'Built-in'), ('custom', 'Custom')], default='esco', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['preferred_label'],
            },
        ),
        migrations.AddField(
            model_name='cvscan',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='matched_preferred_skill_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='matched_required_skill_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='preferred_skill_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='required_skill_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='skill_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
