# Generated by Django 6.0.7 on 2026-10-02 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymenttransaction_usersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='paystack_customer_code',
            new_name='last_payment_reference',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='paystack_transaction_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='paystack_email_token',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='paystack_subscription_code',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Visa/Card')], default="mpesa", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='KES', max_length=5),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('expired', 'Expired')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
