# Generated by Django 6.0.7 on 2026-10-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_paystack_customer_code_usersubscription_last_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='last_payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
