# Generated by Django 6.0.7 on 2026-10-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usersubscription_last_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvscan',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Visa/Card')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='source',
            field=models.CharField(choices=[('esco', 'ESCO'), ('builtin', 'Built-in'), ('custom', 'Custom')], default='esco', max_length=200),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('expired', 'Expired')], default='inactive', max_length=200),
        ),
    ]
